// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbZW-Q6741mkFcibTy44ZM37AtYNC0HZc',
    appId: '1:144028663131:web:6ea5712c190fe6711a6e7e',
    messagingSenderId: '144028663131',
    projectId: 'course-prjct',
    authDomain: 'course-prjct.firebaseapp.com',
    storageBucket: 'course-prjct.appspot.com',
    measurementId: 'G-FJZPZH96PR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuhN2a_dsK51wD13IndmVPjKu1exJFAGk',
    appId: '1:144028663131:android:43fbd7084622d7fb1a6e7e',
    messagingSenderId: '144028663131',
    projectId: 'course-prjct',
    storageBucket: 'course-prjct.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBucN_u4rH2RNDtuJmJXFobvCUGdoEQp_g',
    appId: '1:144028663131:ios:125272f8dc913cd51a6e7e',
    messagingSenderId: '144028663131',
    projectId: 'course-prjct',
    storageBucket: 'course-prjct.appspot.com',
    iosBundleId: 'com.example.flutterFoodDeliverySeries',
  );
}
